export const user = {
    "account_expiry": "2023-12-11",
    "account_type": "free",
    "address": "Thanlyin",
    "advanced_mode": true,
    "allowed_users": 1,
    "email": "myatthiha.ucsy@gmail.com",
    "join_date": "2023-11-27",
    "member_invoicing": "payment_required",
    "name": "Myat Thiha",
    "new_account": false,
    "offer": "payment_required",
    "org_id": "c70f56f1044d4209b59e9329f4bda942",
    "org_name": "Myat Thiha",
    "org_settings": {
      "org_id": "c70f56f1044d4209b59e9329f4bda942",
      "allowed_users": 1,
      "account_type": "free",
    },
    "price_list_mode": "ordinary",
    "role": "owner",
    "show_warning": false,
    "stock_inventory": "payment_required",
    "user_id": "aa834bf14c114e57bd1b9549720daa78",
    "version_settings": {
      "id": 1,
      "offer": true,
      "offer_premium": true,
      "stock_inventory": true,
      "stock_inventory_premium": true,
    }
  }